export const USER_NOT_LOGIN = 'USER_NOT_LOGIN';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_IS_INACTIVE = 'USER_IS_INACTIVE';
export const USER_NOT_PERMISSION = 'USER_NOT_PERMISSION';
export const EMAIL_IS_EXIST = 'EMAIL_IS_EXIST';
export const USER_IS_EXIST = 'USER_IS_EXIST';
export const EMAIL_OR_PASSWORD_IS_INCORRECT = 'EMAIL_OR_PASSWORD_IS_INCORRECT';
export const CONFIRM_PASSWORD_NOT_MATCH = 'CONFIRM_PASSWORD_NOT_MATCH';
